kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "fio-benchmark.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fio-benchmark.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.pvcStorageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvcSize }}
