apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lb
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    postgresql: {{ .Release.Name }}
    role: primary
  sessionAffinity: None
  type: LoadBalancer
