apiVersion: v1
kind: Service
metadata:
  name: {{ include "cnp-loadbalancer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cnp-loadbalancer.labels" . | nindent 4 }}
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    postgresql: {{ include "cnp-loadbalancer.fullname" . }}
    role: primary
  sessionAffinity: None
  type: LoadBalancer
