apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: {{ include "pgbench-benchmark.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgbench-benchmark.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.cnpInstances}}
  postgresql:
    {{- with .Values.cnpPostgreSQLParameters }}
    parameters:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  affinity:
    {{- with .Values.cnpNodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  storage:
    storageClass: {{ .Values.cnpStorageClass }}
    size: {{ .Values.cnpSize }}
