# Copyright 2021 EnterpriseDB Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pgbench-benchmark.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgbench-benchmark.labels" . | nindent 4 }}
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-cnp
        image: {{ .Values.cnpImage }}
        env:
          {{- include "pgbench-benchmark.credentials" . | nindent 10 }}
        command:
        - sh
        - -c
        - until psql -c "SELECT 1"; do echo 'Waiting for {{ include "pgbench-benchmark.service" . }}' sleep 15; done
      - name: pgbench-init
        image: {{ .Values.cnpImage }}
        env:
          {{- include "pgbench-benchmark.credentials" . | nindent 10 }}
        command:
        - pgbench
        args:
        - -i
        - -s
        - {{ .Values.pgbenchScaleFactor | quote }}
      {{- if and ( .Values.pgbenchWarmTime ) ( ne ( .Values.pgbenchWarmTime | quote ) "0" )}}
      - name: pgbench-warm
        image: {{ .Values.cnpImage }}
        env:
          {{- include "pgbench-benchmark.credentials" . | nindent 10 }}
        command:
        - pgbench
        args:
        - -T
        - {{ .Values.pgbenchWarmTime | quote }}
        - -c
        - {{ .Values.pgbenchClients | quote }}
        - -j
        - {{ .Values.pgbenchJobs | quote }}
      {{- end }}
      containers:
      - name: pgbench
        image: {{ .Values.cnpImage }}
        env:
          {{- include "pgbench-benchmark.credentials" . | nindent 10 }}
        command:
        - pgbench
        args:
        - -T
        - {{ .Values.pgbenchTime | quote }}
        - -c
        - {{ .Values.pgbenchClients | quote }}
        - -j
        - {{ .Values.pgbenchJobs | quote }}
      restartPolicy: Never
      {{- with .Values.pgbenchNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
