apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pgbench-benchmark.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgbench-benchmark.labels" . | nindent 4 }}
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-cnp
        image: {{ .Values.cnpImage }}
        env:
        - name: PGHOST
          value: {{ include "pgbench-benchmark.fullname" . }}-rw
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: {{ include "pgbench-benchmark.fullname" . }}-app
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "pgbench-benchmark.fullname" . }}-app
              key: password
        command:
        - sh
        - -c
        - until psql -c "SELECT 1"; do echo 'Waiting for {{ include "pgbench-benchmark.fullname" . }}-rw' sleep 5; done
      - name: pgbench-init
        image: {{ .Values.cnpImage }}
        env:
        - name: PGHOST
          value: {{ include "pgbench-benchmark.fullname" . }}-rw
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: {{ include "pgbench-benchmark.fullname" . }}-app
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "pgbench-benchmark.fullname" . }}-app
              key: password
        command:
        - pgbench
        args:
        - -i
        - -s
        - {{ .Values.pgbenchScaleFactor | quote }}
      {{- if and ( .Values.pgbenchWarmTime ) ( ne ( .Values.pgbenchWarmTime | quote ) "0" )}}
      - name: pgbench-warm
        image: {{ .Values.cnpImage }}
        env:
        - name: PGHOST
          value: {{ include "pgbench-benchmark.fullname" . }}-rw
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: {{ include "pgbench-benchmark.fullname" . }}-app
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "pgbench-benchmark.fullname" . }}-app
              key: password
        command:
        - pgbench
        args:
        - -T
        - {{ .Values.pgbenchWarmTime | quote }}
        - -c 
        - {{ .Values.pgbenchClients | quote }}
        - -j 
        - {{ .Values.pgbenchJobs | quote }}
      {{- end }}
      containers:
      - name: pgbench
        image: {{ .Values.cnpImage }}
        env:
        - name: PGHOST
          value: {{ include "pgbench-benchmark.fullname" . }}-rw
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: {{ include "pgbench-benchmark.fullname" . }}-app
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "pgbench-benchmark.fullname" . }}-app
              key: password
        command:
        - pgbench
        args:
        - -T
        - {{ .Values.pgbenchTime | quote }}
        - -c 
        - {{ .Values.pgbenchClients | quote }}
        - -j 
        - {{ .Values.pgbenchJobs | quote }}
      restartPolicy: Never
      {{- with .Values.pgbenchNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
