# namespace -- The namespace where the benchmark resources are generated.
namespace: default
# istances -- The amount of PostgreSQL instances in the CNP Cluster.
instances: 1
# storageClass -- The storage class used to create PVCs for CNP instances.
storageClass: default
# size -- The size of the PVCs used by CNP instances.
size: 1Gi
# image -- The PostgreSQL image used by CNP and PgBench.
image: quay.io/enterprisedb/postgresql:13.2
# ndeSelector -- Dictionary of key-value pairs used to define the nodes
# where the cluster instances can run; used to avoid pgbench and PostgreSQL
# running on the same node.
nodeSelector:
  workload: postgresql
# postgreSQLParameters -- Dictionary of key-value pairs representing
# PostgreSQL configuration.
postgreSQLParameters:
  shared_buffers: '512MB'
  maintenance_work_mem: '128MB'
  log_checkpoints: "on"
  log_line_prefix: '%m [%p]: u=[%u] db=[%d] app=[%a] c=[%h] s=[%c:%l] tx=[%v:%x] '
  log_lock_waits: "on"
  log_min_duration_statement: '1000'
  log_statement: 'ddl'
  log_temp_files: '1024'
  log_autovacuum_min_duration: '1s'
