# Copyright 2021 EnterpriseDB Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
cnp:
  # -- The amount of PostgreSQL instances in the CNP Cluster.
  instances: 1
  storage:
    # -- The storage class used to create PVCs for CNP instances.
    storageClass: ""
    # -- The size of the PVCs used by CNP instances.
    size: 1Gi
    # -- The PostgreSQL image used by CNP and PgBench.
  image: quay.io/enterprisedb/postgresql:13.2
  # ndeSelector -- Dictionary of key-value pairs used to define the nodes
  # where the cluster instances can run; used to avoid pgbench and PostgreSQL
  # running on the same node.
  nodeSelector:
    workload: postgres
  # cnpMonitoring -- Configures custom queries for monitoring.
  # The arrays accept a Dictionary made by name: string (resource name), key: string (resource data field containing the queries).
  # Documentation on the accepted values: https://docs.enterprisedb.io/cloud-native-postgresql/latest/monitoring/
  monitoring:
    customQueriesConfigMap: []
    customQueriesSecret: []
  # -- Dictionary of key-value pairs representing
  # PostgreSQL configuration.
  postgreSQLParameters:
    shared_buffers: '512MB'
    maintenance_work_mem: '128MB'
    log_checkpoints: "on"
    log_lock_waits: "on"
    log_min_duration_statement: '1000'
    log_statement: 'ddl'
    log_temp_files: '1024'
    log_autovacuum_min_duration: '1s'

  # Configuration of the pooler
  pooler:
    # -- The number of pooler replicas that receive the connections.
    # If >0 the benchmarks are run with connection pooling
    instances: 0
    pgbouncer:
      # -- The pool mode, accepted values: session, transaction
      poolMode: session
      # -- PgBouncer configuration.
      parameters: {}
